# ====================
# Rosetta Build Stage
# ====================
FROM golang:1.15 as rosetta-build-stage

ARG ROSETTA_COMMIT_OR_TAG=v1.0.0

WORKDIR /app
RUN git clone https://github.com/zilliqa/zilliqa-rosetta .
RUN git checkout ${ROSETTA_COMMIT_OR_TAG}
RUN git status
RUN go build main.go
RUN printf "================================================================================\n\n\nRosetta Build Stage Complete\n\n\n================================================================================\n"



# ====================
# Actual Container
# ====================
FROM ubuntu:18.04

# --------------------
# Rosetta Deployment
# --------------------
RUN apt-get update && apt-get install -y ca-certificates
COPY --from=rosetta-build-stage /app/main /rosetta/main
COPY config.local.yaml /rosetta/config.local.yaml
EXPOSE 8080
WORKDIR /rosetta
RUN printf "================================================================================\n\n\nRosetta Deployment Complete\n\n\n================================================================================\n"

CMD ["./main"]
